version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
#     networks:
#       - backend
#   admin:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - 3001:3001
#     networks:
#       - backend


#   microservice:
#     build:
#       context: ./microservicio
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     networks:
#       - backend

# networks:
#   backend:
    